// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Telemetry defines model for Telemetry.
type Telemetry struct {
	// SerialNo Серийный номер устройства
	SerialNo *string `json:"serialNo,omitempty"`

	// Time Время отправки метрики
	Time *string `json:"time,omitempty"`

	// Unit Единица измерения метрики
	Unit *string `json:"unit,omitempty"`

	// Value Значение метрики
	Value *int `json:"value,omitempty"`
}

// DeleteTelemetryParams defines parameters for DeleteTelemetry.
type DeleteTelemetryParams struct {
	// TimeStart Время начала периода выборки метрик
	TimeStart *string `form:"timeStart,omitempty" json:"timeStart,omitempty"`

	// TimeEnd Время окончания периода выборки метрик
	TimeEnd *string `form:"timeEnd,omitempty" json:"timeEnd,omitempty"`
}

// GetTelemetryParams defines parameters for GetTelemetry.
type GetTelemetryParams struct {
	// TimeStart Время начала периода выборки метрик
	TimeStart *string `form:"timeStart,omitempty" json:"timeStart,omitempty"`

	// TimeEnd Время окончания периода выборки метрик
	TimeEnd *string `form:"timeEnd,omitempty" json:"timeEnd,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Удаление телеметрии устройства
	// (DELETE /telemetry/{serialNo})
	DeleteTelemetry(c *gin.Context, serialNo string, params DeleteTelemetryParams)
	// Получение телеметрии устройства
	// (GET /telemetry/{serialNo})
	GetTelemetry(c *gin.Context, serialNo string, params GetTelemetryParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// DeleteTelemetry operation middleware
func (siw *ServerInterfaceWrapper) DeleteTelemetry(c *gin.Context) {

	var err error

	// ------------- Path parameter "serialNo" -------------
	var serialNo string

	err = runtime.BindStyledParameterWithOptions("simple", "serialNo", c.Param("serialNo"), &serialNo, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter serialNo: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteTelemetryParams

	// ------------- Optional query parameter "timeStart" -------------

	err = runtime.BindQueryParameter("form", true, false, "timeStart", c.Request.URL.Query(), &params.TimeStart)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter timeStart: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "timeEnd" -------------

	err = runtime.BindQueryParameter("form", true, false, "timeEnd", c.Request.URL.Query(), &params.TimeEnd)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter timeEnd: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteTelemetry(c, serialNo, params)
}

// GetTelemetry operation middleware
func (siw *ServerInterfaceWrapper) GetTelemetry(c *gin.Context) {

	var err error

	// ------------- Path parameter "serialNo" -------------
	var serialNo string

	err = runtime.BindStyledParameterWithOptions("simple", "serialNo", c.Param("serialNo"), &serialNo, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter serialNo: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTelemetryParams

	// ------------- Optional query parameter "timeStart" -------------

	err = runtime.BindQueryParameter("form", true, false, "timeStart", c.Request.URL.Query(), &params.TimeStart)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter timeStart: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "timeEnd" -------------

	err = runtime.BindQueryParameter("form", true, false, "timeEnd", c.Request.URL.Query(), &params.TimeEnd)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter timeEnd: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTelemetry(c, serialNo, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.DELETE(options.BaseURL+"/telemetry/:serialNo", wrapper.DeleteTelemetry)
	router.GET(options.BaseURL+"/telemetry/:serialNo", wrapper.GetTelemetry)
}
