// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// DeviceRequest defines model for DeviceRequest.
type DeviceRequest struct {
	// Name Название устройства
	Name string `json:"name"`

	// SerialNo Серийный номер устройства
	SerialNo string `json:"serialNo"`

	// Status Статус устройства
	Status string `json:"status"`
}

// DeviceResponse defines model for DeviceResponse.
type DeviceResponse struct {
	// CreatedAt Дата-время добавления в систему
	CreatedAt *string `json:"createdAt,omitempty"`

	// DeviceID Уникальный идентификатор устройства
	DeviceID *openapi_types.UUID `json:"deviceID,omitempty"`

	// DeviceTypeID Уникальный идентификатор типа устройства
	DeviceTypeID *openapi_types.UUID `json:"deviceTypeID,omitempty"`

	// LocationID Уникальный идентификатор локации
	LocationID *openapi_types.UUID `json:"locationID,omitempty"`

	// Name Название устройства
	Name *string `json:"name,omitempty"`

	// SerialNo Серийный номер устройства
	SerialNo *string `json:"serialNo,omitempty"`

	// Status Статус устройства
	Status *string `json:"status,omitempty"`

	// UpdatedAt Дата-время обновления данных
	UpdatedAt *string `json:"updatedAt,omitempty"`

	// UserID Уникальный идентификатор пользователя
	UserID *openapi_types.UUID `json:"userID,omitempty"`
}

// DeviceTypeRequest defines model for DeviceTypeRequest.
type DeviceTypeRequest struct {
	// Name Название типа устройства
	Name string `json:"name"`
}

// DeviceTypeResponse defines model for DeviceTypeResponse.
type DeviceTypeResponse struct {
	// DeviceTypeID Уникальный идентификатор типа устройства
	DeviceTypeID *openapi_types.UUID `json:"deviceTypeID,omitempty"`

	// Name Название типа устройства
	Name *string `json:"name,omitempty"`

	// UserID Уникальный идентификатор пользователя
	UserID *openapi_types.UUID `json:"userID,omitempty"`
}

// DeviceTypesResponse defines model for DeviceTypesResponse.
type DeviceTypesResponse struct {
	// Actions Список типов устройств
	Actions *[]DeviceTypeResponse `json:"actions,omitempty"`
}

// DevicesResponse defines model for DevicesResponse.
type DevicesResponse struct {
	// Actions Список устройств
	Actions *[]DeviceResponse `json:"actions,omitempty"`
}

// LocationRequest defines model for LocationRequest.
type LocationRequest struct {
	// Address Адрес локации пользователя
	Address string `json:"address"`
}

// LocationResponse defines model for LocationResponse.
type LocationResponse struct {
	// Address Адрес локации пользователя
	Address *string `json:"address,omitempty"`

	// LocationID Уникальный идентификатор локации
	LocationID *openapi_types.UUID `json:"locationID,omitempty"`

	// UserID Уникальный идентификатор пользователя
	UserID *openapi_types.UUID `json:"userID,omitempty"`
}

// LocationsResponse defines model for LocationsResponse.
type LocationsResponse struct {
	// Actions Список локаций
	Actions *[]LocationResponse `json:"actions,omitempty"`
}

// UserRequest defines model for UserRequest.
type UserRequest struct {
	// Email E-mail пользователя
	Email *string `json:"email,omitempty"`

	// Name Имя пользователя
	Name string `json:"name"`

	// Patronymic Отчество пользователя
	Patronymic *string `json:"patronymic,omitempty"`

	// PhoneNo Номер телефона пользователя
	PhoneNo string `json:"phoneNo"`

	// Surname Фамилия пользователя
	Surname *string `json:"surname,omitempty"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	// Email E-mail пользователя
	Email *string `json:"email,omitempty"`

	// Name Имя пользователя
	Name string `json:"name"`

	// Patronymic Отчество пользователя
	Patronymic *string `json:"patronymic,omitempty"`

	// PhoneNo Номер телефона пользователя
	PhoneNo string `json:"phoneNo"`

	// Surname Фамилия пользователя
	Surname *string `json:"surname,omitempty"`

	// UserID Уникальный идентификатор пользователя
	UserID *openapi_types.UUID `json:"userID,omitempty"`
}

// PostAuthLoginJSONBody defines parameters for PostAuthLogin.
type PostAuthLoginJSONBody struct {
	// Password Пароль пользователя
	Password string `json:"password"`

	// Username Имя пользователя
	Username string `json:"username"`
}

// GetDevicesParams defines parameters for GetDevices.
type GetDevicesParams struct {
	// DeviceType Фильтр по типу устройства
	DeviceType *openapi_types.UUID `form:"deviceType,omitempty" json:"deviceType,omitempty"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody PostAuthLoginJSONBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = UserRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UserRequest

// CreateDeviceTypeJSONRequestBody defines body for CreateDeviceType for application/json ContentType.
type CreateDeviceTypeJSONRequestBody = DeviceTypeRequest

// UpdateDeviceTypeJSONRequestBody defines body for UpdateDeviceType for application/json ContentType.
type UpdateDeviceTypeJSONRequestBody = DeviceTypeRequest

// CreateLocationJSONRequestBody defines body for CreateLocation for application/json ContentType.
type CreateLocationJSONRequestBody = LocationRequest

// UpdateLocationJSONRequestBody defines body for UpdateLocation for application/json ContentType.
type UpdateLocationJSONRequestBody = LocationRequest

// CreateDeviceJSONRequestBody defines body for CreateDevice for application/json ContentType.
type CreateDeviceJSONRequestBody = DeviceRequest

// PatchDeviceJSONRequestBody defines body for PatchDevice for application/json ContentType.
type PatchDeviceJSONRequestBody = DeviceRequest

// UpdateDeviceJSONRequestBody defines body for UpdateDevice for application/json ContentType.
type UpdateDeviceJSONRequestBody = DeviceRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Аутентификация пользователя
	// (POST /auth/login)
	PostAuthLogin(c *gin.Context)
	// Создание пользователя
	// (POST /users)
	CreateUser(c *gin.Context)
	// Удаление пользователя
	// (DELETE /users/{userID})
	DeleteUser(c *gin.Context, userID openapi_types.UUID)
	// Получение информации о пользователе
	// (GET /users/{userID})
	GetUserById(c *gin.Context, userID openapi_types.UUID)
	// Обновление информации о пользователе
	// (PUT /users/{userID})
	UpdateUser(c *gin.Context, userID openapi_types.UUID)
	// Получение списка типов устройств в локации
	// (GET /users/{userID}/devicetypes)
	GetDeviceTypes(c *gin.Context, userID openapi_types.UUID)
	// Создание типа устройства
	// (POST /users/{userID}/devicetypes)
	CreateDeviceType(c *gin.Context, userID openapi_types.UUID)
	// Удаление типа устройства
	// (DELETE /users/{userID}/devicetypes/{deviceTypeID})
	DeleteDeviceType(c *gin.Context, userID openapi_types.UUID, deviceTypeID openapi_types.UUID)
	// Получение информации о типе устройства
	// (GET /users/{userID}/devicetypes/{deviceTypeID})
	GetDeviceTypeById(c *gin.Context, userID openapi_types.UUID, deviceTypeID openapi_types.UUID)
	// Обновление информации о типе устройства
	// (PUT /users/{userID}/devicetypes/{deviceTypeID})
	UpdateDeviceType(c *gin.Context, userID openapi_types.UUID, deviceTypeID openapi_types.UUID)
	// Получение списка локаций пользователя
	// (GET /users/{userID}/locations)
	GetLocations(c *gin.Context, userID openapi_types.UUID)
	// Создание локации
	// (POST /users/{userID}/locations)
	CreateLocation(c *gin.Context, userID openapi_types.UUID)
	// Удаление локации
	// (DELETE /users/{userID}/locations/{locationID})
	DeleteLocation(c *gin.Context, userID openapi_types.UUID, locationID openapi_types.UUID)
	// Получение информации о локации
	// (GET /users/{userID}/locations/{locationID})
	GetLocationById(c *gin.Context, userID openapi_types.UUID, locationID openapi_types.UUID)
	// Обновление информации о локации
	// (PUT /users/{userID}/locations/{locationID})
	UpdateLocation(c *gin.Context, userID openapi_types.UUID, locationID openapi_types.UUID)
	// Получение списка устройств
	// (GET /users/{userID}/locations/{locationID}/devices)
	GetDevices(c *gin.Context, userID openapi_types.UUID, locationID openapi_types.UUID, params GetDevicesParams)
	// Создание устройства
	// (POST /users/{userID}/locations/{locationID}/devices)
	CreateDevice(c *gin.Context, userID openapi_types.UUID, locationID openapi_types.UUID)
	// Удаление устройства
	// (DELETE /users/{userID}/locations/{locationID}/devices/{deviceID})
	DeleteDevice(c *gin.Context, userID openapi_types.UUID, locationID openapi_types.UUID, deviceID openapi_types.UUID)
	// Получение информации об устройстве
	// (GET /users/{userID}/locations/{locationID}/devices/{deviceID})
	GetDeviceById(c *gin.Context, userID openapi_types.UUID, locationID openapi_types.UUID, deviceID openapi_types.UUID)
	// Частичное обновление информации об устройстве
	// (PATCH /users/{userID}/locations/{locationID}/devices/{deviceID})
	PatchDevice(c *gin.Context, userID openapi_types.UUID, locationID openapi_types.UUID, deviceID openapi_types.UUID)
	// Обновление информации об устройстве
	// (PUT /users/{userID}/locations/{locationID}/devices/{deviceID})
	UpdateDevice(c *gin.Context, userID openapi_types.UUID, locationID openapi_types.UUID, deviceID openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuthLogin(c)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateUser(c)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", c.Param("userID"), &userID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteUser(c, userID)
}

// GetUserById operation middleware
func (siw *ServerInterfaceWrapper) GetUserById(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", c.Param("userID"), &userID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUserById(c, userID)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", c.Param("userID"), &userID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateUser(c, userID)
}

// GetDeviceTypes operation middleware
func (siw *ServerInterfaceWrapper) GetDeviceTypes(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", c.Param("userID"), &userID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDeviceTypes(c, userID)
}

// CreateDeviceType operation middleware
func (siw *ServerInterfaceWrapper) CreateDeviceType(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", c.Param("userID"), &userID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateDeviceType(c, userID)
}

// DeleteDeviceType operation middleware
func (siw *ServerInterfaceWrapper) DeleteDeviceType(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", c.Param("userID"), &userID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "deviceTypeID" -------------
	var deviceTypeID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deviceTypeID", c.Param("deviceTypeID"), &deviceTypeID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter deviceTypeID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteDeviceType(c, userID, deviceTypeID)
}

// GetDeviceTypeById operation middleware
func (siw *ServerInterfaceWrapper) GetDeviceTypeById(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", c.Param("userID"), &userID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "deviceTypeID" -------------
	var deviceTypeID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deviceTypeID", c.Param("deviceTypeID"), &deviceTypeID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter deviceTypeID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDeviceTypeById(c, userID, deviceTypeID)
}

// UpdateDeviceType operation middleware
func (siw *ServerInterfaceWrapper) UpdateDeviceType(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", c.Param("userID"), &userID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "deviceTypeID" -------------
	var deviceTypeID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deviceTypeID", c.Param("deviceTypeID"), &deviceTypeID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter deviceTypeID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateDeviceType(c, userID, deviceTypeID)
}

// GetLocations operation middleware
func (siw *ServerInterfaceWrapper) GetLocations(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", c.Param("userID"), &userID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLocations(c, userID)
}

// CreateLocation operation middleware
func (siw *ServerInterfaceWrapper) CreateLocation(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", c.Param("userID"), &userID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateLocation(c, userID)
}

// DeleteLocation operation middleware
func (siw *ServerInterfaceWrapper) DeleteLocation(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", c.Param("userID"), &userID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "locationID" -------------
	var locationID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "locationID", c.Param("locationID"), &locationID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter locationID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLocation(c, userID, locationID)
}

// GetLocationById operation middleware
func (siw *ServerInterfaceWrapper) GetLocationById(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", c.Param("userID"), &userID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "locationID" -------------
	var locationID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "locationID", c.Param("locationID"), &locationID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter locationID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLocationById(c, userID, locationID)
}

// UpdateLocation operation middleware
func (siw *ServerInterfaceWrapper) UpdateLocation(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", c.Param("userID"), &userID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "locationID" -------------
	var locationID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "locationID", c.Param("locationID"), &locationID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter locationID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLocation(c, userID, locationID)
}

// GetDevices operation middleware
func (siw *ServerInterfaceWrapper) GetDevices(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", c.Param("userID"), &userID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "locationID" -------------
	var locationID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "locationID", c.Param("locationID"), &locationID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter locationID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDevicesParams

	// ------------- Optional query parameter "deviceType" -------------

	err = runtime.BindQueryParameter("form", true, false, "deviceType", c.Request.URL.Query(), &params.DeviceType)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter deviceType: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDevices(c, userID, locationID, params)
}

// CreateDevice operation middleware
func (siw *ServerInterfaceWrapper) CreateDevice(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", c.Param("userID"), &userID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "locationID" -------------
	var locationID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "locationID", c.Param("locationID"), &locationID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter locationID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateDevice(c, userID, locationID)
}

// DeleteDevice operation middleware
func (siw *ServerInterfaceWrapper) DeleteDevice(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", c.Param("userID"), &userID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "locationID" -------------
	var locationID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "locationID", c.Param("locationID"), &locationID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter locationID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "deviceID" -------------
	var deviceID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deviceID", c.Param("deviceID"), &deviceID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter deviceID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteDevice(c, userID, locationID, deviceID)
}

// GetDeviceById operation middleware
func (siw *ServerInterfaceWrapper) GetDeviceById(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", c.Param("userID"), &userID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "locationID" -------------
	var locationID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "locationID", c.Param("locationID"), &locationID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter locationID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "deviceID" -------------
	var deviceID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deviceID", c.Param("deviceID"), &deviceID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter deviceID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDeviceById(c, userID, locationID, deviceID)
}

// PatchDevice operation middleware
func (siw *ServerInterfaceWrapper) PatchDevice(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", c.Param("userID"), &userID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "locationID" -------------
	var locationID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "locationID", c.Param("locationID"), &locationID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter locationID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "deviceID" -------------
	var deviceID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deviceID", c.Param("deviceID"), &deviceID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter deviceID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchDevice(c, userID, locationID, deviceID)
}

// UpdateDevice operation middleware
func (siw *ServerInterfaceWrapper) UpdateDevice(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userID", c.Param("userID"), &userID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "locationID" -------------
	var locationID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "locationID", c.Param("locationID"), &locationID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter locationID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "deviceID" -------------
	var deviceID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deviceID", c.Param("deviceID"), &deviceID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter deviceID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateDevice(c, userID, locationID, deviceID)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	router.POST(options.BaseURL+"/users", wrapper.CreateUser)
	router.DELETE(options.BaseURL+"/users/:userID", wrapper.DeleteUser)
	router.GET(options.BaseURL+"/users/:userID", wrapper.GetUserById)
	router.PUT(options.BaseURL+"/users/:userID", wrapper.UpdateUser)
	router.GET(options.BaseURL+"/users/:userID/devicetypes", wrapper.GetDeviceTypes)
	router.POST(options.BaseURL+"/users/:userID/devicetypes", wrapper.CreateDeviceType)
	router.DELETE(options.BaseURL+"/users/:userID/devicetypes/:deviceTypeID", wrapper.DeleteDeviceType)
	router.GET(options.BaseURL+"/users/:userID/devicetypes/:deviceTypeID", wrapper.GetDeviceTypeById)
	router.PUT(options.BaseURL+"/users/:userID/devicetypes/:deviceTypeID", wrapper.UpdateDeviceType)
	router.GET(options.BaseURL+"/users/:userID/locations", wrapper.GetLocations)
	router.POST(options.BaseURL+"/users/:userID/locations", wrapper.CreateLocation)
	router.DELETE(options.BaseURL+"/users/:userID/locations/:locationID", wrapper.DeleteLocation)
	router.GET(options.BaseURL+"/users/:userID/locations/:locationID", wrapper.GetLocationById)
	router.PUT(options.BaseURL+"/users/:userID/locations/:locationID", wrapper.UpdateLocation)
	router.GET(options.BaseURL+"/users/:userID/locations/:locationID/devices", wrapper.GetDevices)
	router.POST(options.BaseURL+"/users/:userID/locations/:locationID/devices", wrapper.CreateDevice)
	router.DELETE(options.BaseURL+"/users/:userID/locations/:locationID/devices/:deviceID", wrapper.DeleteDevice)
	router.GET(options.BaseURL+"/users/:userID/locations/:locationID/devices/:deviceID", wrapper.GetDeviceById)
	router.PATCH(options.BaseURL+"/users/:userID/locations/:locationID/devices/:deviceID", wrapper.PatchDevice)
	router.PUT(options.BaseURL+"/users/:userID/locations/:locationID/devices/:deviceID", wrapper.UpdateDevice)
}
