@startuml
title Warmhouse Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "Пользователь", "Пользователь системы Warmhouse")
Person(engineer, "Инженер", "Специалист компании Тёплый дом")
System(warmhouse, "Система управления отоплением Warmhouse", "Управление отоплением, мониторинг температуры")

System_Ext(heating_sensor, "Датчики управления отоплением", "")
System_Ext(temp_sensor, "Датчики температуры", "")

Rel(user, warmhouse, "Использует систему для управления отоплением в доме")
Rel(engineer, warmhouse,"Выполняет первичную настройку системы")
Rel(warmhouse, heating_sensor,"Управление датчиками, включение/отключение отопления")
Rel(warmhouse, temp_sensor,"Управление датчиками, получение температуры с датчиков")

@enduml